name: ðŸž Bug Report
description: Report a bug or problem with c:geo direclty to our GitHub tracker
# title: ""
labels: [Bug, Unverified]
# assignees: 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Describe your problem!
      description: Provide a summarized description of what the bug/problem is, that you found.
      placeholder: "
        Examples:\n 
        c:geo crashes when I click on...\n
        I cannot use the function...
        "
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: How to reproduce?
      description: Describe step-by-step how to reproduce the described problem.
      placeholder: "
      Example:\n
      1. Click on xyz\n
      2. Open menu abc\n
      3. ...
      "
    validations:
      required: true
  - type: textarea
    id: actual_result
    attributes:
      label: Actual result after these steps?
      description: Describe what actually happens after the steps above (wrong behavior).
      placeholder: "
      Examples:\n
      The app crashes\n
      Its showing the value xy\n
      Nothing happens
      "
    validations:
      required: true
  - type: textarea
    id: expected_result
    attributes:
      label: Expected result after these steps?
      description: Describe what you expected to happen instead (correct behavior).
      placeholder: "
      Examples:\n
      The app does not crash\n
      Its showing the value ab\n
      The dialog is shown
      "
    validations:
      required: true
  - type: checkboxes
    id: reproducible
    attributes:
      label: Reproducible?
      description: Is the problem reproducible using the steps above?
      options:
        - label: Yes
        - label: No
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: c:geo Version
      description: What version of c:geo are you using? You will find it in c:geo Menu -> About c:geo.
      placeholder: 2021.07.15
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
