name: â­ Feature Request
description: Suggest an idea for a new function in c:geo directly to our GitHub tracker 
# title: ""
labels: [Feature Request, Unverified]
# assignees: 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to tell submit your idea!
  - type: textarea
    id: summary
    attributes:
      label: Tell us your idea!
      description: A clear and detailed description of the function you are missing/would like to see in c:geo.
      placeholder: "
        Examples:\n 
        There is no possibility to...\n
        I'm always frustrated when...\n
        It would be easier to use if
        "
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What solution would you suggest?
      description: Describe your sugggested solution and the way it should be implemented.
      placeholder: "
      Examples:\n
      There should be a new menu item xyz in menu abc, which performs [...]\n
      Change the existing function to include [...]
      "
    validations:
      required: true
  - type: textarea
    id: actual_result
    attributes:
      label: Actual result after these steps?
      description: Describe what actually happens after the steps above (wrong behavior).
      placeholder: "
      Examples:\n
      The app crashes\n
      Its showing the value xy\n
      Nothing happens
      "
    validations:
      required: true
  - type: textarea
    id: expected_result
    attributes:
      label: Expected result after these steps?
      description: Describe what you expected to happen instead (correct behavior).
      placeholder: "
      Examples:\n
      The app does not crash\n
      Its showing the value ab\n
      The dialog is shown
      "
    validations:
      required: true
  - type: checkboxes
    id: reproducible
    attributes:
      label: Reproducible?
      description: Is the problem reproducible using the steps above?
      options:
        - label: "Yes"
        - label: "No"
        - label: "Not sure"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: c:geo Version
      description: What version of c:geo are you using? You will find it in c:geo Menu -> About c:geo.
      placeholder: 2021.07.15
    validations:
      required: true
  - type: textarea
    id: sysinfo
    attributes:
      label: System information
      description: (optional) Providing your system information might be helpful in many cases.
      placeholder: Copy and paste it from c:geo Menu -> About c:geo -> Swipe right to System
      render: shell
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: (optional) You may include screenshots, links to logfiles, reference to other similar issues, projects, sources, etc. 
    validations:
      required: false
